<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Accedi',
        'headline' => 'Accedi',
        'subheadline' => 'Accedi al sito con le tue credenziali',
        'show_subheadline' => false,
        'email_address' => 'Email',
        'password' => 'Password',
        'remember_me' => 'Ricordami',
        'edit' => 'Modifica',
        'button' => 'Continua',
        'forget_password' => 'Password dimenticata?',
        'dont_have_an_account' => 'Non hai un account?',
        'sign_up' => 'Registrati',
        'social_auth_authenticated_message' => 'You have been authenticated via __social_providers_list__. Please login to that network below.',
        'change_email' => 'Cambia Email',
        'couldnt_find_your_account' => 'Account inesistente',
    ],
    'register' => [
        'page_title' => 'Registrati',
        'headline' => 'Registrati',
        'subheadline' => 'Registrati gratuitamente compilando questi dati.',
        'show_subheadline' => true,
        'name' => 'Nome',
        'email_address' => 'Email',
        'password' => 'Password',
        'password_confirmation' => 'Conferma Password',
        'already_have_an_account' => 'Hai già un account?',
        'sign_in' => 'Accedi',
        'button' => 'Continua',
        'email_registration_disabled' => 'Email registration is currently disabled. Please use social login.',
    ],
    'verify' => [
        'page_title' => 'Verifica Account',
        'headline' => 'Verifica la tua mail',
        'subheadline' => 'Prima di procedere, occorre verificare la tua email.',
        'show_subheadline' => true,
        'description' => 'Before proceeding, please check your email for a verification link. If you did not receive the email,',
        'new_request_link' => 'click here to request another',
        'new_link_sent' => 'A new link has been sent to your email address.',
        'or' => 'Or',
        'logout' => 'click here to logout',
    ],
    'passwordConfirm' => [
        'page_title' => 'Confirm Your Password',
        'headline' => 'Confirm Password',
        'subheadline' => 'Be sure to confirm your password below',
        'show_subheadline' => false,
        'password' => 'Password',
        'button' => 'Confirm password',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Request a Password Reset',
        'headline' => 'Reset password',
        'subheadline' => 'Enter your email below to reset your password',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'button' => 'Send password reset link',
        'or' => 'or',
        'return_to_login' => 'return to login',
    ],
    'passwordReset' => [
        'page_title' => 'Reset Your Password',
        'headline' => 'Reset Password',
        'subheadline' => 'Reset your password below',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'password' => 'Password',
        'password_confirm' => 'Confirm Password',
        'button' => 'Reset Password',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Two Factor Challenge',
        'headline_auth' => 'Authentication Code',
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],

];
